language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '12'
install:
  - yarn bootstrap
script:
  - export DEPLOY_DOMAIN=https://preview-${TRAVIS_PULL_REQUEST}-element-ui.surge.sh
  - echo "Deploy to ${DEPLOY_DOMAIN}"
  - curl -X POST ${BOT_URL} -H 'Content-Type:application/json' --data-raw '{"botAction":"Preview", "pr":${TRAVIS_PULL_REQUEST}, "url":"${DEPLOY_DOMAIN}"}'
  - yarn website-build
  - npx surge --project ./website-dist --domain $DEPLOY_DOMAIN
branches:
  only:
    - dev

after_failure:
  - curl -X POST ${BOT_URL} -H 'Content-Type:application/json' --data-raw '{"status":"error", "botAction":"Preview", "pr":${TRAVIS_PULL_REQUEST}}'
