language: node_js
cache: yarn
node_js:
  - '12'
install:
  - yarn bootstrap
script:
  - export DEPLOY_DOMAIN=https://preview-${TRAVIS_PULL_REQUEST}-element-ui.surge.sh
  - echo "Deploy to ${DEPLOY_DOMAIN}"
  - curl -X POST -H 'Content-Type:application/json' ${BOT_URL}
  - yarn website-build
  - npx surge --project ./website-dist --domain $DEPLOY_DOMAIN
branches:
  only:
    - dev

after_failure:
  - curl -X POST ${BOT_URL} -H 'Content-Type:application/json' --data-raw '{"status":"error", "botAction":"Preview", "pr":${TRAVIS_PULL_REQUEST}}'
